### ISSUE TITLE
Possibility to use the same default classes in custom renderers

### ISSUE THREAD

**Issue by dberardo-com** [lukasbach/react-complex-tree#9] opened 2021-10-28 08:46 UTC
the current context passed to `renderItem={({ title, arrow, depth, context, children })` does not contain the related active CSS classes that apply to the button according to the state change.

Would it be possible to get an example of how to reproduce the same exact output as in the default complex tree, using a renderItem override?

**Comment by dberardo-com** [comment] 2021-11-02 16:55
yes, this is what i meant. I would like to use Material UI as basis to style the sidebar, thus i would like to override some classes directly from Javascript.

The only catch in the code above is "where can i get the `renderers`  from within the renderItem callback?

**Comment by dberardo-com** [comment] 2021-11-02 16:58
i have just noticed that using this style object:

`
style={{
                paddingLeft: `${(depth + 1) * 10}px`,
              }}
`

without the call to the renderers object seems to lead to the same default behavior. so that would be enough for my use case i guess

**Comment by lukasbach** [comment] 2021-11-07 21:31
The `renders` prop contains the render logic, if you write your own renderers, you define those values yourself. The variable `renderDepthOffset` just defaults to the number `4`, so if that's all you need, you can just inline the number or use a custom one as you mentioned. You can also use the default renderers by calling `createDefaultRenderers({})` anywhere.

**Comment by dberardo-com** [comment] 2021-11-08 16:13
is it possible to pass a reference to the custom renderer to the tree item that the current node represents?

what i am trying to achieve here is  to open a menu on right click of a tree node and use a renameNode callback when the specific context menu item is selected.

I am having problem firing the "startRenamingItem" method from the current reference to the root tree. So my thought was to handle it directly like we do in the custom interaction object, i.e. accessing the "actions" object and using it in the custom renderer.

Maybe i should document that in a separate issue, but if i pass the TreeRef and call the startRenamingItem method from the ref, i get to see that only the onAbortRenamingItem is called, and not all other on* methods

**Comment by lukasbach** [comment] 2021-11-09 17:50
Sorry, but I'm not completely sure what the problem is. In the render method of the item, one of the props should be a `startRenamingItem` method that you should be able to directly call (https://rct.lukasbach.com/docs/api/interfaces/treeitemrendercontext/#startrenamingitem). But using the imperative ref to the tree should also work...

**Comment by dberardo-com** [comment] 2021-12-01 12:56
hi @lukasbach  i have been experimenting with the complex-tree library and i have managed to create a custom ListItem that reacts to right clicks using the onContextMenu handler and displays a context menu:

![image](https://user-images.githubusercontent.com/65530457/144237923-f7823134-7052-452d-aae8-fcb16158933d.png)

now, i have 2 problems here: 

1 - the underlying tree node of the sidebar is still selected and it is still listening to onclick events, so each time i click on a field in the contextmenu the event gets bubbled to the selected item, and this is definitely not what i want

2 - if i try to add a Rename Item field in the context menu and use the startRenaimingItem function, that will not work, i think for the same reason as in (1), i.e. that the renaming action is called immediately, perhaps because the selectedItem is "clicked" again 

how can i force the selectedItem to still be focused (visually, so the user knows it has been selected) but disconnecting it from the onclick event listener?

**Comment by dberardo-com** [comment] 2021-12-01 13:01
just as extra information: 
- most of the component in the sidebar come from MaterialUI v4
- i have tried adding event.stopPropagation() in the MenuItem onClick handler, but that does not prevent the eventListener on the sidebar node to fire
- the MenuItem is a DOM child  of the sidebar node (thats why the event bubbles to it)

**Comment by dberardo-com** [comment] 2021-12-01 13:56
on problem number 2:
this is the log i get when trying to start renaming the item:

![image](https://user-images.githubusercontent.com/65530457/144246890-69a1066b-7250-42c5-b754-c0f445cfe05f.png)

right after that i see the log of the renamedAborted callback

**Comment by lukasbach** [comment] 2022-04-23 23:01
To avoid bubbling up click events from the context menu to the item renderer, I would first try to call `e.stopPropagation()` directly in the handler of the click events on the menu items, that should avoid the event bubbling altogether. If that doesn't work, you can try to implement [a custom interaction manager](https://rct.lukasbach.com/docs/guides/interaction-modes#custom-interaction-modes) that ignores events when the menu is open.

Regarding the form element being a descendant of a p element: If you start renaming, the item is rendererd in a form container. Looks like some material component you use for something further up renders in a paragraph element, maybe you can prevent that further up. In an accessible tree, you shouldn't have any paragraph elements further up in the tree structure anyways.

**Comment by chalscc** [comment] 2022-08-10 07:23
I'm having the same issue here, onFocusItem is being fired every time you trigger `Drag`, `Drop `or `createInteractiveElementProps: onContextMenu` and is being fired before them, so `e.stopPropagation()` won't work

**Comment by lukasbach** [comment] 2024-04-30 17:06
Will close this since I don't see anything actionable on the original issue. chalscc, if this is still an issue for you, please create a new issue.

**Closed by lukasbach** 2024-04-30 17:06 UTC
